// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNu8aplFqHxkxpWpi259jAAsCFU09N88',
    appId: '1:476908994557:web:ed7b0e3197bd749010a394',
    messagingSenderId: '476908994557',
    projectId: 'movie-app-c554e',
    authDomain: 'movie-app-c554e.firebaseapp.com',
    storageBucket: 'movie-app-c554e.appspot.com',
    measurementId: 'G-KKW75ZK6YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDtAx2Yb_a2SwClRsBZ-pDZGulD6eEFDA',
    appId: '1:476908994557:android:9dc961a177d78fa910a394',
    messagingSenderId: '476908994557',
    projectId: 'movie-app-c554e',
    storageBucket: 'movie-app-c554e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMC904nOaErzMN29xWnuJboq7QM8dCyvE',
    appId: '1:476908994557:ios:c3afc1f3f0e5359210a394',
    messagingSenderId: '476908994557',
    projectId: 'movie-app-c554e',
    storageBucket: 'movie-app-c554e.appspot.com',
    iosBundleId: 'com.example.finalMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMC904nOaErzMN29xWnuJboq7QM8dCyvE',
    appId: '1:476908994557:ios:66e8bf2e259ba99410a394',
    messagingSenderId: '476908994557',
    projectId: 'movie-app-c554e',
    storageBucket: 'movie-app-c554e.appspot.com',
    iosBundleId: 'com.example.finalMovieApp.RunnerTests',
  );
}
